name: autokoopman
channels:
  - conda-forge
  - defaults
dependencies:
  - pysindy=1.3.0
  - pip=24.0
  - matplotlib>=3.3.4
  - sympy>=1.9
  - pandas>=1.1.5
  - pydata-sphinx-theme==0.7.2
  - conda-forge::scikit-learn
  - pip:
    - gpy==1.13.1
    - gpyopt==1.2.6
    - torch==2.2.1
    - sphinx_mdinclude==0.5.1
    - cvxpy==1.4.2
