name: autokoopman
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2023.08.22
  - cffi=1.15.1
  - filelock=3.9.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - jinja2=3.1.2
  - libcxx=16.0.6
  - libffi=3.3
  - libopenblas=0.3.21
  - libprotobuf=3.20.3
  - libsqlite=3.43.2
  - libuv=1.44.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - markupsafe=2.1.1
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.4
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy-base=1.26.0
  - openssl=1.1.1w
  - pip=23.3.1
  - pycparser=2.21
  - python=3.9.0
  - pytorch=2.0.1
  - readline=8.2
  - setuptools=68.2.2
  - sleef=3.5.1
  - sqlite=3.43.2
  - sympy=1.11.1
  - tk=8.6.13
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
      - attrs==22.2.0
      - cmake==3.25.2
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==0.29.33
      - decorator==5.1.1
      - derivative==0.5.3
      - exceptiongroup==1.1.0
      - fonttools==4.38.0
      - gpy==1.10.0
      - gpyopt==1.2.6
      - iniconfig==2.0.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - matplotlib==3.6.3
      - mpmath==1.2.1
      - numpy==1.21.0
      - packaging==23.0
      - pandas==1.5.3
      - paramz==0.9.5
      - pillow==9.4.0
      - pluggy==1.0.0
      - pyparsing==3.0.9
      - pysindy==1.7.2
      - pytest==7.2.1
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - scikit-learn==1.0.2
      - scipy==1.10.0
      - six==1.16.0
      - threadpoolctl==3.1.0
      - tomli==2.0.1
      - tqdm==4.64.1
      - odmd==0.1.3
