name: Sphinx Build
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx_mdinclude pip install pydata-sphinx-theme
          pip install pydmd
          pip install .
      - name: Sphinx build
        run: |
          sphinx-build documentation/sphinx/source _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
